### ISSUE TITLE
Can't assign 0 to next_month()  

### ISSUE THREAD

**Issue by 18z** [spitfire-sidra/DateRanger#4]
I tried to do what described in the subject and get the following results.

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/DateRanger/**init**.py", line 134, in prev_month
    end = end + timedelta(days=1)
UnboundLocalError: local variable 'end' referenced before assignment

**Comment by spitfire-sidra** [comment]
Thank you. I will fix it. :)

**Comment by spitfire-sidra** [comment]
fixed :)
